### ISSUE TITLE
Mail not sent

### ISSUE THREAD

**Issue by Thendeo** [vevedh/mailnotifier#3]
Hi,

I'm using NextCloud 27.0. When creating a flow with mailnotifier, it simply does not work.
For example, I created the following flow : 
When "File created" and "File MIME type matches Office document", send a mail to my address.
No mail is sent, and I don't see any error in logs.

En français : 
Bonjour, 

J'utilise NextCloud 27.0. Lorsque je créer un flow avec mailnotifier, ça ne fonctionne tout simplement pas.
Par exemple, j'ai créer le flow suivant : 
Quand "Fichier créé" et "Le type MIME correspond à un document Office", envoi d'un mail vers mon adresse.
Rien ne se passe, pas de log ni de mail.

**Comment by vevedh** [comment]
Bonjour,

Il faut que le serveur de mail , la partie SMTP soit bien configurée

cordialement

**Comment by vevedh** [comment]
<img width="458" alt="image" src="https://github.com/vevedh/mailnotifier/assets/1430389/61b64fdd-787e-4a20-a8cb-b3577ae7c0e2">

**Comment by vevedh** [comment]
Ah oui je n'ai fait que contrôle  sur le nom de fichier , mais c'est effectivement une idée de faire les autres critères sur le type mime par exemple.
Dans une prochaine version

**Comment by vevedh** [comment]
Ah oui je n'ai fait que le contrôle  sur le nom de fichier (il me semble), mais c'est effectivement une idée de faire les autres critères sur le type mime par exemple.
Dans une prochaine version

**Comment by Thendeo** [comment]
J'ai bien le serveur SMTP configuré, mais effectivement si ça ne fonctionne qu'avec le nom du fichier je vais trouver une autre solution.

Merci !
